# Created using wingetcreate 1.9.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: iCOMcept.7-Zip
PackageVersion: "24.09"
InstallerType: exe
InstallerSwitches:
  Silent: "true"
  SilentWithProgress: "true"
Installers:
- Architecture: x64
  InstallerUrl: https://devpackagesicomcept.blob.core.windows.net/installers/i/iCOMcept/7-Zip/24.09/7z2409-x64.exe
  InstallerSha256: BDD1A33DE78618D16EE4CE148B849932C05D0015491C34887846D431D29F308E
ManifestType: installer
ManifestVersion: 1.9.0
